"""Convert between the guided Theme model and a Waybar style.css.

``generate_css`` is the authoritative direction. ``theme_from_css`` is a best-effort importer
that recognises a small set of properties; anything unrecognised is dropped (the original CSS is
always backed up before overwrite).
"""

from __future__ import annotations

import re

from waybar_configurator.model.catalog import MODULE_CATALOG
from waybar_configurator.model.theme import Theme


def css_id(base_type: str) -> str:
    """Map a Waybar module key to its CSS id (without the leading '#')."""
    if base_type.startswith("custom/"):
        return "custom-" + base_type[len("custom/"):]
    if "/" in base_type:
        return base_type.split("/", 1)[1]
    return base_type


# Reverse map (css id -> module key) for import, built from the catalog.
_ID_TO_TYPE = {css_id(m.key): m.key for m in MODULE_CATALOG}


def _hex_to_rgb(hex_str: str):
    h = hex_str.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    try:
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    except (ValueError, IndexError):
        return 0, 0, 0


def rgba(hex_str: str, alpha: float) -> str:
    r, g, b = _hex_to_rgb(hex_str)
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


# ── Theme -> CSS ──────────────────────────────────────────────────────────────
def generate_css(theme: Theme, used_types) -> str:
    ids = sorted({css_id(t) for t in used_types})
    id_selector = ",\n".join(f"#{i}" for i in ids) if ids else "#clock"
    hover_selector = ",\n".join(f"#{i}:hover" for i in ids) if ids else "#clock:hover"

    group_border = rgba(theme.accent, 0.22)
    group_bg = rgba(theme.background, theme.background_opacity)
    single = theme.bar_style == "single"

    # window#waybar: transparent in "groups" mode (pills carry the background); a
    # single continuous bar carries the background/radius itself.
    window_lines = ["window#waybar {"]
    if single:
        window_lines.append(f"  background-color: {group_bg};")
        if theme.bar_radius > 0:
            window_lines.append(f"  border-radius: {theme.bar_radius}px;")
    else:
        window_lines.append("  background: transparent;")
    if theme.bar_padding_v or theme.bar_padding_h:
        window_lines.append(f"  padding: {theme.bar_padding_v}px {theme.bar_padding_h}px;")
    window_lines.append(f"  color: {theme.foreground};")
    window_lines.append("}")

    # Module groups: rounded pills in "groups" mode, invisible pass-through in "single".
    group_lines = [
        ".modules-left,",
        ".modules-center,",
        ".modules-right {",
    ]
    if single:
        group_lines.append("  background-color: transparent;")
    else:
        group_lines += [
            f"  background-color: {group_bg};",
            f"  border-radius: {theme.group_radius}px;",
            f"  border: 1px solid {group_border};",
        ]
    group_lines += [
        f"  margin: {theme.group_margin_v}px {theme.group_margin_h}px;",
        f"  padding: 0 {theme.group_padding_h}px;",
        "}",
    ]

    lines = [
        "/* ============================================================",
        "   Waybar style — generated by Waybar Configurator",
        "   Edit colours in the app's Appearance tab and re-apply.",
        "   ============================================================ */",
        "",
        "* {",
        "  border: none;",
        "  border-radius: 0;",
        f"  font-family: {theme.font_family};",
        f"  font-size: {theme.font_size}px;",
        "  min-height: 0;",
        "  transition: background-color 0.2s ease, color 0.2s ease;",
        "}",
        "",
        *window_lines,
        "",
        "/* Module group containers */",
        *group_lines,
        "",
        "/* Shared module base */",
        f"{id_selector} {{",
        f"  padding: {theme.padding_v}px {theme.padding_h}px;",
        f"  margin: {theme.module_margin_v}px {theme.module_margin}px;",
        f"  border-radius: {theme.corner_radius}px;",
        f"  color: {theme.foreground};",
        "  background-color: transparent;",
        "}",
        "",
        f"{hover_selector} {{",
        f"  background-color: {rgba(theme.hover, 0.06)};",
        "}",
        "",
        "/* Workspace buttons */",
        "#workspaces button {",
        f"  padding: {theme.padding_v}px {theme.padding_h - 3}px;",
        f"  margin: {theme.module_margin_v}px {theme.module_margin}px;",
        f"  border-radius: {theme.corner_radius}px;",
        f"  color: {theme.foreground};",
        "  background-color: transparent;",
    ]
    if theme.workspace_min_width > 0:
        lines.append(f"  min-width: {theme.workspace_min_width}px;")
    lines += [
        "}",
        "#workspaces button.focused,",
        "#workspaces button.active {",
        f"  background-color: {rgba(theme.accent, 0.18)};",
        "  font-weight: bold;",
        "}",
        "#workspaces button.urgent {",
        f"  background-color: {rgba('#f87171', 0.22)};",
        "  color: #fca5a5;",
        "}",
        "",
        "/* Warning / critical states */",
        ".warning { color: #fbbf24; }",
        ".critical {",
        "  color: #f87171;",
        f"  background-color: {rgba('#f87171', 0.10)};",
        "}",
    ]

    if theme.module_colors:
        lines += ["", "/* Per-module colours */"]
        for base_type, color in sorted(theme.module_colors.items()):
            if base_type not in used_types:
                continue
            lines.append(f"#{css_id(base_type)} {{ color: {color}; }}")

    lines += [
        "",
        "/* Tooltip */",
        "tooltip {",
        f"  background-color: {rgba(theme.tooltip_background, 0.96)};",
        f"  border: 1px solid {rgba(theme.accent, 0.25)};",
        f"  border-radius: {theme.corner_radius}px;",
        f"  color: {theme.tooltip_foreground};",
        "}",
        "tooltip label {",
        f"  color: {theme.tooltip_foreground};",
        "  padding: 2px 4px;",
        "}",
        "",
    ]
    return "\n".join(lines)


# ── CSS -> Theme (best-effort import) ─────────────────────────────────────────
def _rgba_to_hex_alpha(match_str: str):
    nums = re.findall(r"[\d.]+", match_str)
    if len(nums) < 3:
        return None
    r, g, b = (int(float(nums[i])) for i in range(3))
    alpha = float(nums[3]) if len(nums) >= 4 else 1.0
    return f"#{r:02x}{g:02x}{b:02x}", alpha


def theme_from_css(css: str) -> Theme:
    theme = Theme()

    m = re.search(r"font-family:\s*([^;]+);", css)
    if m:
        theme.font_family = m.group(1).strip().replace('"', "")
    m = re.search(r"font-size:\s*(\d+)px", css)
    if m:
        theme.font_size = int(m.group(1))

    m = re.search(r"window#waybar\s*{[^}]*?color:\s*(#[0-9a-fA-F]+)", css, re.S)
    if m:
        theme.foreground = m.group(1)

    # Module-group background + border accent.
    m = re.search(r"\.modules-\w+[^{]*{([^}]*)}", css, re.S)
    block = m.group(1) if m else css
    bg = re.search(r"background-color:\s*(rgba\([^)]*\)|#[0-9a-fA-F]+)", block)
    if bg:
        val = bg.group(1)
        if val.startswith("rgba"):
            res = _rgba_to_hex_alpha(val)
            if res:
                theme.background, theme.background_opacity = res
        else:
            theme.background = val
    bd = re.search(r"border:[^;]*?(rgba\([^)]*\)|#[0-9a-fA-F]+)", block)
    if bd and bd.group(1).startswith("rgba"):
        res = _rgba_to_hex_alpha(bd.group(1))
        if res:
            theme.accent = res[0]
    rad = re.search(r"border-radius:\s*(\d+)px", block)
    if rad:
        theme.group_radius = int(rad.group(1))

    # Per-module colours: "#id { ... color: #hex }".
    for mid, color in re.findall(r"#([\w-]+)\s*{[^}]*?color:\s*(#[0-9a-fA-F]+)[^}]*}", css):
        base_type = _ID_TO_TYPE.get(mid)
        if base_type and mid not in ("waybar",):
            theme.module_colors[base_type] = color
    return theme
